{
     "openapi": "3.0.0",
     "info": {
       "title": "API Documentation",
       "description": "API da aplicação do TFD",
       "version": "1.0.0"
     },
     "servers":[
        {
            "url":"http://localhost:3004",
            "description":"rota Principal"
        }
    ],
    "paths": {
        
        "/paciente":{
            "get":{
                "summary":"listar Pacientes.",
                "description":"Rota para realizar o cadastro de pacientes",
                "tags":["Paciente"],
                "responses":{"200":{"description":"OK","content":{"application/json":{
                    "schema":{
                        "type":"object",
                        "$ref":"#/components/schemas/cadastrar_paciente"
                    }
                }}},
                "401":{
                    "description": "Token não informado"
                },
                "404":{
                    "description":"Paciente não encontrado"
                }
                }
                
            },
            "post":{
                "summary":"Cadastro de Paciente",
                "description":"Rota para realizar o cadastro de pacientes",
                "tags":["Paciente"],
                "security":[{"bearerAuth": []}],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/cadastrar_paciente"
                            },
                            "examples":{
                                "Paciente":{
                                    "value":{
                                        "DataNascimento": "1990-01-15T00:00:00.000Z",
                                        "NumeroCPF": "12345678901",
                                        "NumeroRG": "78901234",
                                        "OrgaoEmissor": "SSP",
                                        "NumeroCartaoSUS": 987654321,
                                        "NumeroTituloEleitor": 12345,
                                        "EleitorUF": "SP",
                                        "NomePaciente": "João da Silva",
                                        "NomeSocial": "",
                                        "Sexo": "M",
                                        "Idade": 32,
                                        "raca": "Branca",
                                        "cor": "Pardo",
                                        "Sangue": "O+",
                                        "DataCadastro": "2023-05-17T00:00:00.000Z",
                                        "NomePaiouResponsavel": "",
                                        "NomeMae": "Maria Oliveira",
                                        "EstadoCivil": "Solteiro(a)",
                                        "Endereco": "Rua das Flores, 123",
                                        "Bairro": "Centro",
                                        "Cidade": "São Paulo",
                                        "UF": "SP",
                                        "CEP": 12345678,
                                        "Referencia": "Próximo ao supermercado",
                                        "Celular": [
                                          {
                                            "Numero": 987654321
                                          }
                                        ],
                                        "Acompanhantes": [
                                          {
                                            "NomeAcompanhante": "Ana",
                                            "NumeroCPF": "98765432109",
                                            "NumeroRG": "12345678",
                                            "DataNascimento": "1985-03-10"
                                          }
                                        ],
                                        "Email": "joao.silva@example.com",
                                        "identZona": "Zona Urbana",
                                        "TratamentoAtual": "Tratamento X",
                                        "Ocupacao": "Engenheiro",
                                        "GrauEstudo": "Ensino Superior",
                                        "Conta": 12345
                                      }
                                      
                                }
                            }
                        }
                        
                    }
                },
                
                "responses":{
                    "401":{
                        "description": "Token não informado"
                    },
                    "404":{
                        "description":"Paciente não encontrado"
                    },
                    "200":{
                        "description":"OK",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "$ref":"#/components/schemas/cadastrar_paciente"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/paciente/{id}":{
            "get":{
                "summary":"listar Paciente pelo identificador.",
                "description":"Rota para realizar a busca de um paciente pelo identificador",
                "tags":["Paciente"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"path",
                        "description":"Id do paciente para buscar",
                        "required":true
                    }
                ],
                "responses":{"200":{"description":"OK","content":{"application/json":{
                    "schema":{
                        "type":"object",
                        "$ref":"#/components/schemas/cadastrar_paciente"
                    }
                }}},
                "401":{
                    "description": "Token não informado"
                },
                "404":{
                    "description":"Paciente não encontrado"
                }
                }
                
            },
                
                "responses":{
                    "401":{
                        "description": "Token não informado"
                    },
                    "404":{
                        "description":"Paciente não encontrado"
                    },
                    "200":{
                        "description":"OK",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "$ref":"#/components/schemas/cadastrar_paciente"
                                }
                            }
                        }
                    }
                }
            },


        "/func":{
            "get": {
                "summary": "Listas Paciente",
                "description":"Lista todos os funcionários cadastrados na base de dados",
                "tags":["Funcionario"],
                "responses":{"200":{"description":"Sucesso","content":{"application/json":{
                    "schema":{
                        "type":"object",
                        "$ref":"#/components/schemas/cadastrar_funcionario"
                    }
                }}}}
            },
            "post": {
                "summary": "Cadastro Funcionário",
                "description":"Insere um novo funcionario no banco de dados",
                "tags":["Funcionario"],
                "requestBody":{
                    "required":true,
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/cadastrar_funcionario"
                            },
                            "examples":{
                                "Funcionario":{
                                    "value":{
                                        "nomeFuncionario": "Nome do Funcionário",
                                        "CPF": "123.456.789-00",
                                        "Rg": 1234567,
                                        "NumeroMatricula": 98765,
                                        "NumeroPortaria": 54321,
                                        "Cidade": "Nome da Cidade",
                                        "UfCidade": "UF",
                                        "CEP": "12345-678",
                                        "Celular": [
                                          {
                                            "Numero": 987654321
                                          },
                                          {
                                            "Numero": 123456789
                                          }
                                        ],
                                        "AtividadeExercida": "Atividade",
                                        "DataNascimento": "01/01/1990",
                                        "CentroDeSaude": "Nome do Centro de Saúde",
                                        "DataCadastro": "01/01/2023",
                                        "Observacao": "Observação sobre o funcionário"
                                      }                                      
                                }
                            }
                        }
                    }
                }
        }
        },


        "/med":{
            "get":{
                "summary":"Listar Médicos",
                "description":"Lista os médicos no banco de dados",
                "tags":["Médico"],
                "responses":{
                    "200":{"description":"OK", "content":{
                            "application/json":{
                                "schema":{
                                    "$ref":"#/components/schemas/cadastrar_medico"
                                }
                            }
                    }   }
                }
            },
            "post":{
                "summary":"Cadastro de Medicos",
                "description":"Insere um novo medico no banco de dados",
                "tags":["Médico"],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/cadastrar_medico"
                            },
                            "examples":{
                                "Medico":{
                                    "value":{
                                        "IdentProfissional": 1,
                                        "NomeCompleto": "João da Silva",
                                        "NumeroRegistro": 123456,
                                        "UF": "SP",
                                        "CPF": "12345678900",
                                        "DataNascimento": "1980-01-01",
                                        "Cargo": "Médico",
                                        "CodigoCBO": "3231-10",
                                        "Especialidades": [
                                          {
                                            "Nome": "Cirurgia Geral"
                                          },
                                          {
                                            "Nome": "Medicina Interna"
                                          }
                                        ],
                                        "CentroDeSaude": "Hospital Central de São Paulo",
                                        "DataCadastro": "2023-11-08",
                                        "Afastamento": "Não"
                                      }
                                      
                                }
                            }
                        }
                    }
                }
            }
        },

        "/processo":{
            "get":{
                "summary":"Listagem de Processos",
                "description":"Lista os processo no banco de dados",
                "tags":["Processo"],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/cadastrar_processo"
                            }
                        }
                    }
                }
            },
            "post":{
                "summary":"Cadastro de Processo",
                "description":"Insere um novo processo no banco de dados",
                "tags":["Processo"],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/cadastrar_processo"
                            },
                            "examples": {
                                "IdPaciente": 1,
                                "DataViagem": 1654321000,
                                "DataAgendamento": "2023-05-19T10:00:00.000Z",
                                "PrevisaoRetorno": "2023-05-20T15:30:00.000Z",
                                "TipoAtendimento": 2,
                                "Especialidade": 3,
                                "IdFuncionario": 3,
                                "IdMedico": 3,
                                "Entidade": 3,
                                "LocalOrigem": "Hospital ABC2",
                                "LocalAtendimento": "Hospital Central de São Paulo",
                                "Destino": "São Paulo",
                                "TipoDeslocamento": "Avião",
                                "EmpresaTransporte": "Companhia Aérea XYZ",
                                "TotalPassagem": {
                                  "ida": 500,
                                  "volta": 450
                                },
                                "IdentTrajeto": "ABC123XYZ",
                                "ObsAtendimento": "Nenhum",
                                "ObsPassagemAerea": "Preferência por janela",
                                "createdAt": "2023-05-19T19:12:42.910Z"
                              }
                              
                        }
                    }
                }
            }
        }

        
    },
    "components":{
        "schemas":{
            "cadastrar_paciente":{
                "type": "object",
                "properties":
                    {
                        "_id": { "type": "number" },
                        "DataNascimento": { "type": "number" },
                        "numeroCPF": { "type": "string" },
                        "orgaoEmissor": { "type": "string" },
                        "NumeroCartaoSUS": { "type": "number" },
                        "NumeroTituloEleitor": { "type": "number" },
                        "UF": { "type": "string" },
                        "NomePaciente": { "type": "string" },
                        "NomeSocial": { "type": "string" },
                        "Sexo": { "type": "string" },
                        "Idade": { "type": "number" },
                        "Sangue": { "type": "string" },
                        "DataCadastro": { "type": "date" },
                        "NomePaiouResponsavel": { "type": "string" },
                        "NomeMae": { "type": "string" },
                        "EstadoCivil": { "type": "string" },
                        "Endereco": { "type": "string" },
                        "Bairro": { "type": "string" },
                        "UfCidade": { "type": "string" },
                        "CEP": { "type": "string" },
                        "Celular": [{ "Numero": { "type": "string" } }],
                        "Email": { "type": "string" },
                        "identZona": { "type": "string" },
                        "TratamentoAtual": { "type": "string" },
                        "Ocupacao": { "type": "string" },
                        "GrauEstudo": { "type": "string" },
                        "Conta": { "type": "number" },
                        "__v": { "type": "number" }
                      } 
                
            },
            "cadastrar_funcionario":{
                "type": "object",
                "properties":
                {
                    "_id": { "type": "number" },
                    "nomeFuncionario": { "type": "string" },
                    "CPF": { "type": "string" },
                    "Rg": { "type": "number" },
                    "NumeroMatricula": { "type": "number" },
                    "NumeroPortaria": { "type": "number" },
                    "Cidade": { "type": "string" },
                    "UfCidade": { "type": "string" },
                    "CEP": { "type": "string" },
                    "Celular": [
                      {
                        "Numero": { "type": "number" }
                        
                      },
                      {
                        "Numero": { "type": "number" }
                        
                      }
                    ],
                    "AtividadeExercida": { "type": "string" },
                    "DataNascimento": { "type": "string" },
                    "CentroDeSaude": { "type": "string" },
                    "DataCadastro": { "type": "string" },
                    "Observação": { "type": "string" },
                    "__v": { "type": "number" }
                  }
            },
            "cadastrar_medico":{
                "type":"object",
                "properties":{
                    "_id": { "type": "number" },
                    "IdentProfissional": { "type": "number" },
                    "NomeCompleto": { "type": "string" },
                    "NumeroRegistro": { "type": "number" },
                    "UF": { "type": "number" },
                    "CPF": { "type": "string" },
                    "DataNascimento": { "type": "string" },
                    "Cargo": { "type": "string" },
                    "CodigoCBO": { "type": "string" },
                    "Especialidades": [
                      {
                        "Nome": { "type": "string" },
                        "_id": { "type": "object", "$oid": { "type": "string" } }
                      },
                      {
                        "Nome": { "type": "string" },
                        "_id": { "type": "object", "$oid": { "type": "string" } }
                      }
                    ],
                    "CentroDeSaude": { "type": "string" },
                    "DataCadastro": { "type": "string" },
                    "Afastamento": { "type": "string" },
                    "__v": { "type": "number" }
                  }
                  
            },
            "cadastrar_processo":{
                "type": "object",
                "properties":{
                    "_id": {"type": "number"},
                    "IdPaciente": {"type": "number"},
                    "DataViagem": {"type": "date"},
                    "DataAgendamento": {"type": "date"},
                    "PrevisaoRetorno": {"type": "date"},
                    "TipoAtendimento": {"type": "number"},
                    "Especialidade": {"type": "number"},
                    "IdFuncionario": {"type": "number"},
                    "IdMedico": {"type": "number"},
                    "Entidade": {"type": "number"},
                    "LocalOrigem": {"type": "string"},
                    "CidadeDestino": {"type": "string"},
                    "TipoDeslocamento": {"type": "string"},
                    "EmpresaTransporte": {"type": "string"},
                    "TotalPassagem": {"type": "string"},
                    "IdentTrajeto": {"type": "string"},
                    "ObsAtendimento": {"type": "string"},
                    "ObsPassagemAerea": {"type": "string"},
                    "createdAt": {"type": "date"},
                    "__v": {"type": "number"}
                  }
                  
            }
        },
        "securitySchemes":{
            "bearerAuth":{
                "type": "http",
                "scheme": "bearer",
                "bearerFormat":"JWT"
            }
        }
    }
}